# -*- coding: utf-8 -*-
import logging
from odoo import models

_logger = logging.getLogger(__name__)


def _get_warehouse_from_location(env, location, company_id):
    """
    Resolve the warehouse that owns a given stock location.

    Strategy:
    1. picking_type_id on the quant's location is not available directly,
       so we match by checking if the location is a child of any warehouse's
       view_location_id, or is the warehouse's lot_stock_id.

    Returns the warehouse record or False.
    """
    warehouses = env['stock.warehouse'].search([
        ('analytic_account_id', '!=', False),
        ('company_id', '=', company_id),
    ])
    for wh in warehouses:
        # Direct match: this is the main stock location
        if location.id == wh.lot_stock_id.id:
            return wh
        # Child-of match: location is somewhere under this warehouse's tree
        try:
            if location._child_of(wh.view_location_id):
                return wh
        except Exception:
            # _child_of may not exist in all Odoo versions; fall back to parent walk
            loc = location
            while loc:
                if loc.id == wh.view_location_id.id:
                    return wh
                loc = loc.location_id or False
    return False


def _apply_analytic_to_move(move, analytic, label=''):
    """
    Stamp analytic_distribution = {analytic_id: 100.0} on all account.move.line
    records that belong to *move* and have an account set.

    Uses sudo() + context flags to bypass the posted-move write restriction.
    Lines already carrying this analytic are skipped.
    """
    if not move or not analytic:
        return
    key = str(analytic.id)
    for line in move.line_ids.filtered(lambda l: l.account_id):
        existing = line.analytic_distribution or {}
        if key not in existing:
            new_dist = dict(existing)
            new_dist[key] = 100.0
            try:
                line.sudo().with_context(
                    check_move_validity=False,
                    skip_account_move_synchronization=True,
                ).analytic_distribution = new_dist
                _logger.debug(
                    'Inventory analytic %s → %s line %s (%s)',
                    analytic.name, label, line.id,
                    line.account_id.code,
                )
            except Exception as e:
                _logger.warning(
                    'Could not apply inventory analytic to %s line %s: %s',
                    label, line.id, e,
                )


class StockQuant(models.Model):
    _inherit = 'stock.quant'

    def _apply_inventory(self):
        """
        Override _apply_inventory to stamp the warehouse analytic account
        on all STJ (inventory adjustment) journal entries generated by
        this physical inventory update.

        Odoo calls stock.quant._apply_inventory() when the user clicks
        "Apply All" or validates a physical inventory count. This creates
        stock.move records which in turn generate account.move (STJ/) entries
        for valued products.

        We capture the set of account.move records that exist before and
        after calling super(), then apply the correct warehouse analytic to
        any newly created ones.
        """
        # Snapshot existing account.move IDs so we can detect new ones
        existing_move_ids = set(
            self.env['account.move'].search([
                ('journal_id.type', '=', 'general'),
            ]).ids
        )

        result = super()._apply_inventory()

        # Find all account.move records created by this inventory adjustment
        new_moves = self.env['account.move'].search([
            ('id', 'not in', list(existing_move_ids)),
            ('journal_id.type', '=', 'general'),
        ])

        if not new_moves:
            return result

        for move in new_moves:
            # Identify the stock location from the move's reference name or
            # linked stock moves. We resolve the warehouse from stock.move lines.
            analytic = self._get_inventory_analytic(move)
            if analytic:
                _apply_analytic_to_move(
                    move, analytic,
                    label='inventory_adj_%s' % (move.name or move.id),
                )
            else:
                _logger.warning(
                    'Inventory analytic: no warehouse analytic found for STJ move %s',
                    move.name,
                )

        return result

    def _get_inventory_analytic(self, account_move):
        """
        Resolve the analytic account for an inventory-adjustment account.move.

        Strategy:
        1. Find stock.move records that generated this account.move
           via stock_move.account_move_ids (Odoo 17+) or account_move_id.
        2. From the stock.move, read location_id (source) or
           location_dest_id (destination) to find the owning warehouse.
        3. Fall back to self's own location_id if stock.move link is absent.
        """
        env = self.env
        company_id = account_move.company_id.id

        # Try to find stock.move(s) linked to this account.move
        stock_moves = env['stock.move'].search([
            ('account_move_ids', 'in', [account_move.id]),
        ], limit=10)

        # Older Odoo stores a single account_move_id on stock.move
        if not stock_moves:
            stock_moves = env['stock.move'].search([
                ('account_move_id', '=', account_move.id),
            ], limit=10)

        for sm in stock_moves:
            # For inventory adjustments the destination is the stock location
            for loc in (sm.location_dest_id, sm.location_id):
                if not loc:
                    continue
                wh = _get_warehouse_from_location(env, loc, company_id)
                if wh:
                    _logger.debug(
                        'Inventory analytic: move %s → stock.move %s → loc %s → wh %s → %s',
                        account_move.name, sm.id, loc.name,
                        wh.name, wh.analytic_account_id.name,
                    )
                    return wh.analytic_account_id

        # Fallback: try the quants in self that triggered this adjustment.
        # self may be a recordset of multiple quants; try each location.
        for quant in self:
            loc = quant.location_id
            if not loc:
                continue
            wh = _get_warehouse_from_location(env, loc, company_id)
            if wh:
                _logger.debug(
                    'Inventory analytic (quant fallback): quant %s → loc %s → wh %s → %s',
                    quant.id, loc.name, wh.name, wh.analytic_account_id.name,
                )
                return wh.analytic_account_id

        return False