{
    'name': 'Custom Cash Book, Day Book, Bank Book Financial Reports',
    'version': '19.0.1.0.0',
    'category': 'Invoicing Management',
    'summary': 'Custom Cash Book, Day Book and Bank Book Report For Odoo 19',
    'description': 'Custom Cash Book, Day Book and Bank Book Report For Odoo 19',
    'sequence': '10',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'views/custom_daily_reports.xml',
        'wizard/daybook.xml',
        'wizard/cashbook.xml',
        'wizard/bankbook.xml',
        'report/reports.xml',
        'report/report_daybook.xml',
        'report/report_cashbook.xml',
        'report/report_bankbook.xml',
    ],
    'installable': True,
    'application': False,
}
